Resolve several issues: - Issue 115 - Incorrent package naming and version in manpage - Move nblock_write to ddsnap - Make zumastor arch indep - Correct manpage issues - Add VISUAL as env variable for buildcurrent so it works   with new versions of dpkg-buildpackage

diff --git a/zumastor/lib/zumastor/common b/zumastor/lib/zumastor/common
--- a/zumastor/lib/zumastor/common
+++ b/zumastor/lib/zumastor/common
@@ -568,7 +568,7 @@ function send_to_fifo {
 	local -r data=$2
 
 	if [[ $nonblock == "yes" ]]; then
-		echo $data | /lib/zumastor/nblock_write $fifo || { echo "error writing to $fifo"; return 1; }
+		echo $data | /sbin/nblock_write $fifo || { echo "error writing to $fifo"; return 1; }
 	else
 		[[ -e $fifo ]] || { echo "$fifo does not exist"; return 1; }
 		[[ -p $fifo ]] || { echo "$fifo not a fifo"; return 1; }
