A non-blocking open nblock_write.c helper program so zumastor master can't hang writing to target triggers.

diff --git a/zumastor/lib/zumastor/common b/zumastor/lib/zumastor/common
--- a/zumastor/lib/zumastor/common
+++ b/zumastor/lib/zumastor/common
@@ -395,3 +395,21 @@ function treeprint {
 	done
 	popd >/dev/null
 }
+
+function send_to_fifo {
+	local nonblock
+	[[ $1 == "-n" ]] && { nonblock=yes; shift; }
+	[ $# -eq 2 ] || { echo "$0: wrong argument count ($#: $@) in call: ${FUNCNAME[@]}"; exit 1; }
+	local -r fifo=$1
+	local -r data=$2
+
+	if [[ $nonblock == "yes" ]]; then
+		echo $data | /lib/zumastor/nblock_write $fifo || { echo "error writing to $fifo"; return 1; }
+	else
+		[[ -e $fifo ]] || { echo "$fifo does not exist"; return 1; }
+		[[ -p $fifo ]] || { echo "$fifo not a fifo"; return 1; }
+		[[ -w $fifo ]] || { echo "$fifo not writable"; return 1; }
+		echo $data >$fifo || { echo "error writing to $fifo"; return 1; }
+	fi
+}
+
