Use stderr for errors.  Fix passing of two-word commands to ddsnap.  Added new status options.

diff --git a/hotcakes/scripts/ddutil b/hotcakes/scripts/ddutil
--- a/hotcakes/scripts/ddutil
+++ b/hotcakes/scripts/ddutil
@@ -85,6 +85,9 @@ usage_status()
 {
     echo "$@status [<option>...] [<snapshot>]"
     echo "    -v, --verbose             Print all sharing statistics"
+    echo "    --last                    Print the newest snapshot id"
+    echo "    --list                    Print all active snapshot ids"
+    echo "    --size                    Print the size of the origin device"
 }
 
 usage_delta_changelist()
@@ -133,6 +136,7 @@ usage_subcommands_short()
 {
     echo ""
     echo "subcommands:"
+
     echo "   initialize         Initialize the snashot store"
     echo "   agent              Start the snapshot agent"
     echo "   server             Start the snapshot server"
@@ -153,6 +157,7 @@ usage_subcommands_long()
 {
     echo ""
     echo "subcommands:"
+
     echo ""
     usage_initialize "  "
     echo ""
@@ -225,14 +230,14 @@ while [ $# -ge 1 ]; do
 
         --)
             shift
-            # if there's no next arg that's ok, empty command will print usage
+            # if there's no next arg that's ok, an empty command will print usage
             subcommand="$1"
             shift
             break
             ;;
 
         *)
-            echo "$0: unexpected argument $1"
+            echo "$0: unexpected argument $1" >& 2
             usage
             exit 1
             ;;
@@ -248,12 +253,12 @@ fi
 
 if [ X"${subcommand}" = X"delta" ]; then
     if [ $# -lt 1 ]; then
-        echo "$0: no delta subcommand specified"
-        usage
-        usage_subcommands_short
+        echo "$0: incomplete ${subcommand} command" >&2
+        usage >& 2
+        usage_subcommands_short >& 2
         exit 0
     fi
-    subcommand="delta $1"
+    subcommand="${subcommand} $1"
     shift
 fi
 
@@ -291,7 +296,7 @@ case "${subcommand}" in
         minargs='0'
         maxargs='1'
         shortopts='v'
-        longopts='verbose'
+        longopts='verbose,last,list,size'
         ;;
 
     priority|usecount|delta\ apply)
@@ -386,21 +391,21 @@ done
 
 
 if [ $# -lt ${minargs} ]; then
-    echo "$0: too few arguments to subcommand \"${subcommand}\""
-    "${usage_func}" "usage: $0 "
-    exit 2
+    echo "$0: too few arguments to subcommand \"${subcommand}\"" >& 2
+    "${usage_func}" "usage: $0 " >& 2
+    exit 3
 fi
 if [ $# -gt ${maxargs} ]; then
-    echo "$0: too many arguments to subcommand \"${subcommand}\""
-    "${usage_func}" "usage: $0 "
-    exit 2
+    echo "$0: too many arguments to subcommand \"${subcommand}\"" >& 2
+    "${usage_func}" "usage: $0 " >& 2
+    exit 3
 fi
 
 
 # read user configuration
 if ! [ -r "${conf_file}" ]; then
-    echo "$0: unable to read configuration file \"${conf_file}\""
-    exit 3
+    echo "$0: unable to read configuration file \"${conf_file}\"" >& 2
+    exit 4
 fi
 
 . "${conf_file}"
@@ -409,55 +414,55 @@ fi
 case "${subcommand}" in
     initialize)
         if dmsetup ls 2> /dev/null | egrep "^${map_origin}	" > /dev/null; then
-            echo "$0: snapshot origin device ${map_origin} already in use"
-            exit 3
+            echo "$0: snapshot origin device ${map_origin} already in use" >& 2
+            exit 5
         fi
 
         if [ X"${dev_meta}" = X"" ] || [ X"${dev_meta}" = X"${dev_snapstore}" ]; then
-            ddsnap "${subcommand}" ${suboptions} "${dev_snapstore}" "${dev_origin}"
+            ddsnap ${subcommand} ${suboptions} "${dev_snapstore}" "${dev_origin}"
         else
-            ddsnap "${subcommand}" ${suboptions} "${dev_snapstore}" "${dev_origin}" "${dev_meta}"
+            ddsnap ${subcommand} ${suboptions} "${dev_snapstore}" "${dev_origin}" "${dev_meta}"
         fi
         if [ $? -ne 0 ]; then
-            echo "$0: mkddsnap failed to initialize the snapshot store"
-            exit 3
+            echo "$0: mkddsnap failed to initialize the snapshot store" >& 2
+            exit 5
         fi
         ;;
 
     create)
         originbase="`echo \"${dev_origin}\" | sed -e 's@^.*/@@'`"
         if ! egrep "${originbase}$" /proc/partitions > /dev/null 2>&1; then
-            echo "$0: snapshot origin device ${dev_origin} not detected in /proc/partitions"
-            exit 3
+            echo "$0: snapshot origin device ${dev_origin} not detected in /proc/partitions" >& 2
+            exit 5
         fi
         originblocks="`egrep \" ${originbase}$\" /proc/partitions | awk '{ print $3 }'`"
         originsize="`expr 2 '*' \"${originblocks}\"`"
 
         if [ X"$1" = X"-1" ]; then
             if dmsetup ls 2> /dev/null | egrep "^${map_origin}	" > /dev/null; then
-                echo "$0: snapshot origin device ${map_origin} already in use"
-                exit 3
+                echo "$0: snapshot origin device ${map_origin} already in use" >& 2
+                exit 5
             fi
             echo 0 "${originsize}" ddsnap "${dev_snapstore}" "${dev_origin}" "${agent_sockpath}" "$1" |
                 dmsetup create "${map_origin}"
             if [ $? -ne 0 ]; then
-                echo "$0: dmsetup failed to create origin mapping"
-                exit 3
+                echo "$0: dmsetup failed to create origin mapping" >& 2
+                exit 5
             fi
         else
             if dmsetup ls 2> /dev/null | egrep "^${map_snap_stem}$1	" > /dev/null; then
-                echo "$0: snapshot device ${map_snap_stem}$1 already in use"
-                exit 3
+                echo "$0: snapshot device ${map_snap_stem}$1 already in use" >& 2
+                exit 5
             fi
-            if ! ddsnap "${subcommand}" ${suboptions} "${ddsnapd_sockpath}" "$1"; then
-                echo "$0: ddsnap unable to create snapshot $1"
-                exit 4
+            if ! ddsnap ${subcommand} ${suboptions} "${ddsnapd_sockpath}" "$1"; then
+                echo "$0: ddsnap unable to create snapshot $1" >& 2
+                exit 5
             fi
             echo 0 "${originsize}" ddsnap "${dev_snapstore}" "${dev_origin}" "${agent_sockpath}" "$1" |
                 dmsetup create "${map_snap_stem}$1"
             if [ $? -ne 0 ]; then
-                echo "$0: dmsetup failed to create snapshot $1 mapping"
-                exit 3
+                echo "$0: dmsetup failed to create snapshot $1 mapping" >& 2
+                exit 5
             fi
         fi
         ;;
@@ -467,44 +472,45 @@ case "${subcommand}" in
             dmsetup remove "${map_origin}"
         else
             dmsetup remove "${map_snap_stem}$1"
-            ddsnap "${subcommand}" ${suboptions} "${ddsnapd_sockpath}" "$@"
+            ddsnap ${subcommand} ${suboptions} "${ddsnapd_sockpath}" "$@"
         fi
         ;;
 
     list|priority|usecount|delta\ changelist|status)
-        ddsnap "${subcommand}" ${suboptions} "${ddsnapd_sockpath}" "$@"
+        ddsnap ${subcommand} ${suboptions} "${ddsnapd_sockpath}" "$@"
         ;;
 
     delta\ create)
-        ddsnap "${subcommand}" ${suboptions} "$1" "$2" "$3" "$4"
+        ddsnap ${subcommand} ${suboptions} "$1" "$2" "$3" "$4"
         ;;
 
     delta\ apply)
-        ddsnap "${subcommand}" ${suboptions} "$1" "${map_path}/${map_snap_stem}$2"
+        ddsnap ${subcommand} ${suboptions} "$1" "${map_path}/${map_snap_stem}$2" "${map_path}/${map_origin}"
         ;;
 
     delta\ send)
-        ddsnap "${subcommand}" ${suboptions} "${ddsnapd_sockpath}" "$1" "$2" "${map_path}/${map_snap_stem}$1" "${map_path}/${map_snap_stem}$2" "$3" "$4"
+        ddsnap ${subcommand} ${suboptions} "${ddsnapd_sockpath}" "$1" "$2" "${map_path}/${map_snap_stem}$1" "${map_path}/${map_snap_stem}$2" "$3" "$4"
         ;;
 
     delta\ listen)
-        ddsnap "${subcommand}" ${suboptions} -l "${ddsnap_delta_log}" -p "${ddsnap_delta_pid}" "${map_path}/${map_snap_stem}" "$@"
+        ddsnap ${subcommand} ${suboptions} -l "${ddsnap_delta_log}" -p "${ddsnap_delta_pid}" "${map_path}/${map_snap_stem}" "${map_path}/${map_origin}" "$@"
         ;;
 
     agent)
-        ddsnap "${subcommand}" ${suboptions} -l "${ddsnap_agent_log}" -p "${ddsnap_agent_pid}" "${agent_sockpath}" 
+        ddsnap ${subcommand} ${suboptions} -l "${ddsnap_agent_log}" -p "${ddsnap_agent_pid}" "${agent_sockpath}"
         ;;
 
     server)
         if [ X"${dev_meta}" = X"" ] || [ X"${dev_meta}" = X"${dev_snapstore}" ]; then
-            ddsnap "${subcommand}" ${suboptions} -l "${ddsnap_server_log}" -p "${ddsnap_server_pid}" "${dev_snapstore}" "${dev_origin}" "${agent_sockpath}" "${ddsnapd_sockpath}"
+            ddsnap ${subcommand} ${suboptions} -l "${ddsnap_server_log}" -p "${ddsnap_server_pid}" "${dev_snapstore}" "${dev_origin}" "${agent_sockpath}" "${ddsnapd_sockpath}"
         else
-            ddsnap "${subcommand}" ${suboptions} -l "${ddsnap_server_log}" -p "${ddsnap_server_pid}" "${dev_snapstore}" "${dev_origin}" "${dev_meta}" "${agent_sockpath}" "${ddsnapd_sockpath}"
+            ddsnap ${subcommand} ${suboptions} -l "${ddsnap_server_log}" -p "${ddsnap_server_pid}" "${dev_snapstore}" "${dev_origin}" "${dev_meta}" "${agent_sockpath}" "${ddsnapd_sockpath}"
         fi
         ;;
 
     *)
-        echo "$0: unhandled subcommand \"${subcommand}\""
+        echo "$0: unhandled subcommand \"${subcommand}\"" >& 2
+        exit 2
         ;;
 esac
 
