Added squashed snapshot detection, fixed init script bug with no snapshots

diff --git a/trunk/zumastor/lib/zumastor/common b/trunk/zumastor/lib/zumastor/common
--- a/trunk/zumastor/lib/zumastor/common
+++ b/trunk/zumastor/lib/zumastor/common
@@ -194,7 +194,16 @@ function create_device {
 	local -r odev=$info/device/origin
 	local -r name=$(volume_name $vol $id)
 
-	# FIXME TODO: input checking
+	if [[ $id -gt -1 ]]; then
+		ddsnap status --state $server $id
+		case $? in
+		0) ;; # success
+		1) log "error: snapshot $name not found"; return 1 ;;
+		2) log "error: snapshot $name squashed"; return 1 ;;
+		9) log "error: checking snapshot state"; return 1 ;;
+		*) log "error: unknown state return code $?"; return 1 ;;
+		esac
+	fi 
 
 	echo 0 $size ddsnap $sdev $odev $agent $id | dmsetup create $name || return 1
 }
@@ -224,20 +233,22 @@ function mount_device {
 	local -r vol=$1
 	local -r id=$2
 	local -r name=$(volume_name $vol $id)
+	local -r device=/dev/mapper/$name
 	local mount=${MOUNTS}/$name
 	local options=ro
 
 	# to support mounting arbitrary snapshots to the unqualified volume mountpoint
 	[[ $3 == "unqualified" ]] && mount=${MOUNTS}/$vol
 	[[ $3 == "rw" ]] && options="rw,errors=remount-ro,usrquota,grpquota"
+	[[ -r $device ]] || { echo "unable to open device $device"; return 1; }
 
 	test -d $mount || mkdir $mount || return 1
 
 	# mount ro, umount, and re-mount to work around free blocks bug in ext3
-	mount -o ro /dev/mapper/$name $mount || { sleep 3; mount -o ro /dev/mapper/$name $mount || return 1; }
-	umount /dev/mapper/$name && \
-	mount -o $options /dev/mapper/$name $mount || \
-		{ echo "unable to mount /dev/mapper/$name on $mount"; return 1; }
+	mount -o ro $device $mount || { sleep 3; mount -o ro $device $mount || return 1; }
+	umount $device && \
+	mount -o $options $device $mount || \
+		{ echo "unable to mount $device on $mount"; return 1; }
 }
 
 function umount_device {
@@ -258,6 +269,7 @@ function remove_device {
 	local -r vol=$1
 	local -r id=$2
 	local -r name=$(volume_name $vol $id)
+	local output
 
 	dmsetup remove $name || return 1
 }
