fixed some replication issues, call sync to keep replication closer to reality in lieu of freezing the filesystem, updated todo

diff --git a/zumastor/bin/zumastor b/zumastor/bin/zumastor
--- a/zumastor/bin/zumastor
+++ b/zumastor/bin/zumastor
@@ -110,8 +110,9 @@ function new_target_snapshot {
 
 	echo "`date`: new snapshot will be '$next'"
 
+	# need to create the device in order for ddsnap delta send to work
 	create_device $vol $next
-	mount_device $vol $next
+	# but we don't need to mount it
 
 	send_to_fifo $target_fifo $next || return 1
 
@@ -129,23 +130,6 @@ function run_remote  {
 	else
 		echo $command | ssh $host
 	fi
-}
-
-function replicate_wait {
-	[ $# -eq 2 ] || { echo "$0: wrong argument count ($#: $@) in call: ${FUNCNAME[@]}"; exit 1; }
-	local -r vol=$1
-	local -r host=$2
-	local -r period_file=$VOLUMES/$vol/targets/$host/period
-	local period
-
-	[[ -e $period_file ]] || { echo "$0: couldn't open $period_file"; return 1; }
-	
-	# FIXME TODO check value
-	read period < $period_file
-	# FIXME TODO subtract the amount of time which has passed since start of cycle
-
-	sleep $period
-	return 0
 }
 
 function usecount_increment {
@@ -197,18 +181,20 @@ function replicate_snapshot {
 	local -r hold_file=$target_dir/hold
 	local -r server=$SERVERS/$vol
 	local -r port_file=$target_dir/port
+	local -r myhost=`hostname -s`
 	local old_snap
 	local rem_snap
 	local port
 
 	echo "`date`: replication for snapshot '$snap' on volume '$vol' to '$host'"
 
+	rem_snap=$(run_remote $host "cat $VOLUMES/$vol/source/hostname") && [[ $rem_snap = $myhost ]] || \
+		{ echo "set '$myhost' as source for '$vol' on '$host' first!"; return 1; }
+
 	# FIXME TODO - input checking here
 
 	if [ -e $send_file ]; then
 		echo "$0: $send_file shouldn't exist"
-		# !!! FIXME handle some other way - abort
-		#replicate_wait $vol $host || echo "$0: error waiting"
 		return 1
 	fi
 
@@ -222,13 +208,9 @@ function replicate_snapshot {
 
 	echo "remote snapshot id $rem_snap listen started"
 
-	# increment the use count on the snapshot
-	usecount_increment $vol $snap
-	usecount_increment $vol $old_snap
-
 	# send the changes since the last snapshot via ddsnap delta send
-	ddsnap delta send -r -g 5 $server $old_snap $snap /dev/mapper/$vol\($old_snap\) \
-		/dev/mapper/$vol\($snap\) $rem_snap $host
+	echo running ddsnap delta send -r -g 5 $server $old_snap $snap /dev/mapper/$vol $rem_snap $host
+	ddsnap delta send -r -g 5 $server $old_snap $snap /dev/mapper/$vol $rem_snap $host
 
 	run_remote $host "zumastor receive $vol $port done"
 
@@ -237,9 +219,8 @@ function replicate_snapshot {
 	# !!! FIXME TODO this is racy, we should save state by journaling
 	mv $send_file $hold_file
 
-	remove_device $vol $old_snap
+	# this will remove if reference count is zero
 	usecount_decrement $vol $old_snap
-	replicate_wait $vol $host || echo "$0: error waiting"
 }
 
 function run_master {
@@ -280,27 +261,43 @@ function run_target {
 	local -r vol=$1
 	local -r host=$2
 	local -r fifo=$VOLUMES/$vol/targets/$host/trigger
+	local -r period_file=$VOLUMES/$vol/targets/$host/period
 	local -r log=${LOGS}/${vol}-target-${host}.log
 	local -r master_fifo=$VOLUMES/$vol/master/trigger
 	local snap
 	local state
+	local period
 
-	[ -r $fifo ] && [ -p $fifo ] || { echo "$0: target replication trigger '$fifo' is missing"; return 1; }
+	read period < $period_file || { echo "$0: couldn't read $period_file" >> $log; return 1; }
+	[[ $period -ge 0 ]] || { echo "$0: invalid period '$period' specified" >> $log; return 1; }
+
+	[ -r $fifo ] && [ -p $fifo ] || { echo "$0: target replication trigger '$fifo' is missing" >> $log; return 1; }
 
 	# daemonize (close stdin, stdout, stderr)
-	#exec 0</dev/null 1>/dev/null 2>/dev/null
+	exec 0</dev/null 1>/dev/null 2>/dev/null
 
 	# we reopen the log for each write so rotation works
-	echo "`date`: starting replication daemon of volume '$vol' to target '$host': pid $$" >> $log
+	echo "`date`: starting replication daemon of volume '$vol' to target '$host' period '$period': pid $$" >> $log
 	while true; do
-		# !!! Implement skipping to most recent snapshot if there is a backlog
-		read snap <$fifo || exit 1
+		[[ -r $fifo ]] || { echo "$0: $fifo not readable" >> $log; return 1; }
+		# !!! FIXME TODO Implement skipping to most recent snapshot if there is a backlog
+		read snap <$fifo || snap=timeout
+
+		if [[ $snap = "timeout" ]]; then
+			echo "`date`: $period sec timeout elapsed, waking up" >> $log
+			snap=wakeup
+		fi
+
 		if [[ $snap = "wakeup" ]]; then
 			[[ -e $master_fifo ]] || echo "$0: error: wakeup on non master volume '$vol'" >> $log
 			# woke state
 			send_to_fifo $master_fifo "target $host" || echo $0: error writing to fifo >> $log
 		else
-			replicate_snapshot $vol $host $snap >> $log 2>&1
+			replicate_snapshot $vol $host $snap >> $log 2>&1 && { \
+			# FIXME TODO subtract time thats passed since period
+			sleep $period; \
+			send_to_fifo $master_fifo "target $host" || echo $0: error writing to fifo >> $log; \
+			}
 		fi
 	done &
 }
@@ -419,12 +416,18 @@ function forget_volume {
 }
 
 function define_target {
-	[ $# -eq 3 ] || { echo "$0: wrong argument count ($#: $@) in call: ${FUNCNAME[@]}"; exit 1; }
+	[ $# -eq 4 ] || { echo "$0: wrong argument count ($#: $@) in call: ${FUNCNAME[@]}"; exit 1; }
 	local -r vol=$1
 	local -r host=$2
 	local -r port=$3
-	local -r period=$3
+	local -r period=$4
 	local -r path=$VOLUMES/$vol/targets/$host
+
+	local -r myhost=`hostname -s`
+	local rem_host
+
+	rem_host=$(run_remote $host "cat $VOLUMES/$vol/source/hostname") && [[ $rem_host = $myhost ]] || \
+		{ echo "set '$myhost' (not '$rem_host') as source for '$vol' on '$host' first!"; return 1; }
 
 	mkdir $path || return 1
 	mkfifo $path/trigger || return 1
@@ -446,10 +449,14 @@ function forget_target {
 function forget_source {
 	[ $# -eq 1 ] || { echo "$0: wrong argument count ($#: $@) in call: ${FUNCNAME[@]}"; exit 1; }
 	local -r vol=$1
+	local hold
+
+	# !!! FIXME TODO clean up replication in progress
+	hold=$(cat $VOLUMES/$vol/source/hold)
+	[[ $hold -ge 0 ]] && usecount_decrement $vol $hold
 
 	rm -rf $VOLUMES/$vol/source || return 1
-	# !!! FIXME TODO clean up snapshots properly
-
+	return 0
 }
 
 function set_master {
@@ -552,22 +559,36 @@ function replication_cycle {
 	local -r sock=${SERVERS}/$vol
 	local -r path=${VOLUMES}/$vol
 	local -r holdfile=$path/source/hold
+	local -r log=${LOGS}/${vol}-source.log
 	local next
 	local hold
 
+	echo "`date`: replication cycle beginning" >> $log
 	hold=$(cat $holdfile) || { echo "inital replication cycle"; next=0; }
 
 	# FIXME TODO - don't assume next snapshot number
 	[[ $hold -ge 0 ]] && next=$(( $hold + 1 ))
+	echo "`date`: create device beginning" >> $log
+	create_device $vol $next >> $log 2>&1
 
-	create_device $vol $next
-	mount_device $vol $next
+	echo "`date`: sync device beginning" >> $log
+	sync >> $log 2>&1
+
+	echo "`date`: mount device beginning" >> $log
+	mount_device $vol $next >> $log 2>&1
 
 	# !!! FIXME TODO NFS failover here
 
+	echo "`date`: setting holdfile to $next" >> $log
 	echo $next > $holdfile
 
-	[[ $hold -ge 0 ]] && { umount_device $vol $hold; remove_device $vol $hold; }
+	echo "`date`: umount/remove snapshot $hold " >> $log
+	if [[ $hold -ge 0 ]]; then
+		umount_device $vol $hold >> $log 2>&1
+		remove_device $vol $hold >> $log 2>&1
+		usecount_decrement $vol $hold >> $log 2>&1
+	fi
+	echo "`date`: cycle complete" >> $log
 
 }
 
