added taking 0 snapshot back in, lost in r274

diff --git a/zumastor/bin/zumastor b/zumastor/bin/zumastor
--- a/zumastor/bin/zumastor
+++ b/zumastor/bin/zumastor
@@ -802,6 +802,10 @@ define)
 				|| { echo "$0: init volume '$vol' failed"; exit 1; }
 
 			echo "Successfully created and initialized volume '$vol'."
+
+			create_snapshot $vol 0 || { echo "$0: error with initial snapshot"; exit 1; }
+			echo 0 > $VOLUMES/$vol/zero
+
 			echo "You can now create a filesystem on /dev/mapper/$vol"
 		fi
 
