Implement chained replication. With the change, when zumastor receives a replication request, it checks if it is an intermediate node of a chained replication. If it is, 'zumastor target' daemon will set the newest replicated snapshot it receives from upstream as the snapshot to be replicated to downstream.

diff --git a/trunk/zumastor/bin/zumastor b/trunk/zumastor/bin/zumastor
--- a/trunk/zumastor/bin/zumastor
+++ b/trunk/zumastor/bin/zumastor
@@ -34,7 +34,10 @@ function drop_snapshot {
 		ddsnap delete $server $snap || { log "failed to delete snapshot '$vol($snap)'"; return 1; }
 		return 0
 	fi
-	[[ $usecount -eq 1 ]] || { log "trying to remove snapshot with usecount '$usecount'"; return 1; }
+	if [[ $usecount -gt 1 ]]; then
+		ddsnap usecount $server $snap -1 || { log "couldn't decrease usecount for vol '$vol' snap '$snap'"; return 1; }
+		return 0
+	fi
 	remove_device $vol $snap || { log "remove device failed for $vol($snap) "; return 1; }
 
 	# FIXME we wait for the usecount to hit zero
@@ -177,15 +180,16 @@ function run_remote  {
 	fi
 }
 
-#function usecount_increment {
-#	[[ $# -eq 2 ]] || { echo "$0: wrong argument count ($#: $@) in call: ${FUNCNAME[@]}"; exit 1; }
-#	local -r vol=$1
-#	local -r snap=$2
-#	local -r server=$SERVERS/$vol
-#
-#	# FIXME TODO input chekcing
-#	ddsnap usecount $server $snap 1 || return 1
-#}
+function usecount_increment {
+	[[ $# -eq 2 ]] || { echo "$0: wrong argument count ($#: $@) in call: ${FUNCNAME[@]}"; exit 1; }
+	local -r vol=$1
+	local -r snap=$2
+	local -r server=$SERVERS/$vol
+
+	# FIXME TODO input chekcing
+	ddsnap usecount $server $snap 1 >&/dev/null || return 1
+	return 0
+}
 
 # replicate_snapshot
 # called from target zumastor daemon (run_target)
@@ -376,6 +380,9 @@ function run_target {
 	local -r log=${LOGS}/$vol/target-${host}.log
 	local -r master_fifo=$VOLUMES/$vol/master/trigger
 	local snap="" period starttime newperiod delay status
+	local -r source_holdfile=$VOLUMES/$vol/source/hold
+	local -r target_holdfile=$VOLUMES/$vol/targets/$host/hold
+	local repsnap oldsnap
 
 	[ -r $fifo ] && [ -p $fifo ] || { log "target replication trigger '$fifo' is missing" $log; return 1; }
 
@@ -383,7 +390,7 @@ function run_target {
 
 	if [[ ! -z $period ]]; then
 		if verify_valid_number $period; then
-			(zumastor replicate $vol $host --nowait &) # double fork to prevent sigchld interrupting read
+			(zumastor replicate $vol $host --nowait >> $log 2>&1 &) # double fork to prevent sigchld interrupting read
 		else
 			log "invalid period '$period' specified" $log
 			return 1
@@ -405,26 +412,50 @@ function run_target {
 			read snap <$fifo && break || log "couldn't read from $fifo"
 			sleep 1
 		done
+
+		if [[ $snap == -1 ]] && [[ ! -e $master_fifo ]] && [[ -f $source_holdfile ]]; then
+			repsnap=
+			oldsnap=-1
+			# this is an intermediate node of a chanined replication,
+			# so use the newest completely replicated snapshot
+			read -d" " repsnap 2>/dev/null <$source_holdfile
+			if [[ -z $repsnap ]]; then
+				log "no fully replicated snapshot available, skip the replication" $log
+			else
+				# check if this is a newer snapshot
+				read -d" " oldsnap 2>/dev/null <$target_holdfile
+				if [[ $repsnap -le $oldsnap ]]; then
+					log "no newer replicated snapshot, skip the replication" $log
+				else
+					usecount_increment $vol $repsnap && snap=$repsnap
+				fi
+			fi
+		fi
+
 		pkill -f "zumastor replicate $vol $host --delay"
 		starttime=$(now)
 
-		replicate_snapshot $vol $host $snap >> $log 2>&1
-		status=$?
-		if [[ $status -eq 0 ]]; then #success 
-			log "successfully replicated snapshot $snap" $log
-			snap=""
-		elif [[ $status -eq 13 ]]; then
-			log "successfully replicated resumed snapshot" $log
-			snap=""
-		elif [[ $status -eq 3 ]]; then
-			log "replication error on snapshot $snap, not retrying" $log
-			drop_snapshot $vol $snap >>$log 2>&1
-			snap="" # FIXME perhaps we should trigger a new replication cycle here
+		if [[ $snap != -1 ]]; then
+			replicate_snapshot $vol $host $snap >> $log 2>&1
+			status=$?
+			if [[ $status -eq 0 ]]; then #success 
+				log "successfully replicated snapshot $snap" $log
+				snap=""
+			elif [[ $status -eq 13 ]]; then
+				log "successfully replicated resumed snapshot" $log
+				snap=""
+			elif [[ $status -eq 3 ]]; then
+				log "replication error on snapshot $snap, not retrying" $log
+				drop_snapshot $vol $snap >>$log 2>&1
+				snap="" # FIXME perhaps we should trigger a new replication cycle here
+			else
+				log "replicate error on snapshot $snap: $?" $log
+				# FIXME TODO add retry code here, for now we retry forever
+				sleep 1
+				continue
+			fi
 		else
-			log "replicate error on snapshot $snap: $?" $log
-			# FIXME TODO add retry code here, for now we retry forever
-			sleep 1
-			continue
+			snap=""
 		fi
 
 		read newperiod <$period_file 2>/dev/null || newperiod=
@@ -448,7 +479,7 @@ function run_target {
 			fi
 			# background this so the master and target daemons can't both block
 			log "scheduling replication cycle in ${delay}s" $log
-			(zumastor replicate $vol $host --delay $delay --nowait &) # double fork to prevent sigchld interrupting read
+			(zumastor replicate $vol $host --delay $delay --nowait >> $log 2>&1 &) # double fork to prevent sigchld interrupting read
 		fi
 	done &
 }
@@ -716,15 +747,18 @@ function trigger_replication {
 	local -r target_fifo=$VOLUMES/$vol/targets/$host/trigger
 	local -r master_fifo=$VOLUMES/$vol/master/trigger
 
-
-	if [[ -z $snap ]]; then
+	if [[ ! -z $snap ]]; then
+		# increase reference count to pin snapshot
+		usecount_increment $vol $snap
+		# send specified snapshot
+		send_to_fifo $target_fifo $snap || return 1
+	elif [[ -e $master_fifo ]]; then
 		# no snapshot specified, asking the master for a new one
 		send_to_fifo $master_fifo "target/$host" || return 1
 	else
-		# increase reference count to pin snapshot
-		#usecount_increment $vol $snap
-		# send specified snapshot
-		send_to_fifo $target_fifo $snap || return 1
+		# This is an intermediate node of a chained replication. Currently, run_target 
+		# daemon synchronizes all of the replication, so let it do the job.
+		send_to_fifo $target_fifo -1 || return 1
 	fi
 }
 
@@ -814,7 +848,7 @@ function nag_daemon {
 		fi
 
 		log "sending wakeup for volume $remote_vol on $host:" $log
-		run_remote $host "echo target/$MYHOSTNAME > $VOLUMES/$remote_vol/master/trigger" >> $log 2>&1
+		run_remote $host "zumastor replicate $remote_vol $MYHOSTNAME --nowait" >> $log 2>&1 &
 		sleep $period
 	done &
 }
