Fix typo on call to replicate_snapshot and make sure we start replication on start target when an automatic replication interval is specified.  Also cleaned up drop_snapshot called from replicate_snapshot errors because this is handled by the error handler in run_target.

diff --git a/trunk/zumastor/bin/zumastor b/trunk/zumastor/bin/zumastor
--- a/trunk/zumastor/bin/zumastor
+++ b/trunk/zumastor/bin/zumastor
@@ -223,12 +223,10 @@ function replicate_snapshot {
 	rem_snap=$(run_remote $host "cat $VOLUMES/$vol/source/hostname") && [[ $rem_snap == $MYHOSTNAME ]] || \
 		{ log "set '$MYHOSTNAME' as source for '$vol' on '$host' first!"; remove_device $vol $snap; return 1; }
 
-	read port <$port_file || { log "error reading port from '$port_file'"; \
-		rm $send_file; drop_snapshot $vol $snap; return 1; }
+	read port <$port_file || { log "error reading port from '$port_file'"; return 1; }
 
 	rem_snap=$(run_remote $host "zumastor receive $vol $port start") || \
-		{ log "starting remote snapshot receive failed"; \
-		rm $send_file; drop_snapshot $vol $snap; return 1; }
+		{ log "starting remote snapshot receive failed"; return 1; }
 
 	log "remote listen for volume '$vol' on '$host:$port' started"
 
@@ -240,16 +238,12 @@ function replicate_snapshot {
 	ddsnap transmit $server $host:$port -r -g 5 $old_snap $snap -p $send_file
 	if [[ $? -ne 0 ]]; then
 		log "transmit $server $host:$port $old_snap $snap failed"
-		rm $send_file
-		drop_snapshot $vol $snap
 		return 1
 	fi
 
 	run_remote $host "zumastor receive $vol $port done $snap"
 	if [[ $? -ne 0 ]]; then
 		log "zumastor receive $vol $port done $snap failed"
-		rm $send_file
-		drop_snapshot $vol $snap
 		return 1
 	fi
 
@@ -316,10 +310,18 @@ function run_target {
 	local -r sleep_pid=$VOLUMES/$vol/targets/$host/.sleeppid
 	local snap state period spid
 
-	[[ -e $period_file ]] && read period <$period_file || log "no period specified" $log
-	[[ -z $period ]] || [[ $period -ge 0 ]] || { log "invalid period '$period' specified" $log; return 1; }
-
 	[ -r $fifo ] && [ -p $fifo ] || { log "target replication trigger '$fifo' is missing" $log; return 1; }
+
+	[[ -e $period_file ]] && read period <$period_file || log "no period specified" $log
+
+	if [[ ! -z $period ]]; then
+		if verify_valid_number $period; then
+			trigger_replication $vol $host $snap
+		else
+			log "invalid period '$period' specified" $log
+			return 1
+		fi
+	fi
 
 	# daemonize (close stdin, stdout, stderr)
 	exec 0</dev/null 1>/dev/null 2>/dev/null
@@ -343,7 +345,7 @@ function run_target {
 			sleep 1 # not necesary, just in case
 		done
 
-		replicate_snapshot $vol $host $snap >> $log 2>&1 &&
+		replicate_snapshot $vol $host $snap >> $log 2>&1
 		if [[ $? == 0 ]]; then #success 
 			log "successfully replicated snapshot $snap" $log
 			[[ -z $period ]] || (
@@ -360,7 +362,7 @@ function run_target {
 				exit
 			) &
 		else
-			log "replicate error on snapshot $snap" $log
+			log "replicate error on snapshot $snap: $?" $log
 			drop_snapshot $vol $snap >> $log 2>&1
 		fi
 	done &
