Support arbitrary mountpoints, per Issue 17, "Let the admin specify mount point."

diff --git a/trunk/zumastor/bin/zumastor b/trunk/zumastor/bin/zumastor
--- a/trunk/zumastor/bin/zumastor
+++ b/trunk/zumastor/bin/zumastor
@@ -450,11 +450,12 @@ function stop_target {
 }
 
 function define_volume {
-	[ $# -eq 3 ] || [ $# -eq 4 ] || { echo "$0: wrong argument count ($#: $@) in call: ${FUNCNAME[@]}"; exit 1; }
+	[ $# -eq 4 ] || [ $# -eq 5 ] || { echo "$0: wrong argument count ($#: $@) in call: ${FUNCNAME[@]}"; exit 1; }
 	local -r vol=$1
 	local -r odev=$2
-	local -r sdev=$3
-	local -r mdev=$4
+	local -r mountpoint=$3
+	local -r sdev=$4
+	local -r mdev=$5
 	local -r path=$VOLUMES/$vol
 	local -r sock=${SERVERS}/$vol
 
@@ -465,6 +466,8 @@ function define_volume {
 	ln -sf $sdev $path/device/snapstore || return 1
 	[ -z $mdev ] || ln -sf $mdev $path/device/meta || return 1
 	mkdir $path/targets || return 1
+	mkdir $path/filesystem
+	echo $mountpoint >$path/filesystem/mountpoint
 
 	start_volume $vol || { echo start failed; return 1; }
 	create_device $vol -1 || { echo create failed; return 1; }
@@ -785,10 +788,11 @@ define)
 		declare args metadev init
 		declare blocksize=4k
 		declare chunksize=16k
-		declare usage="Usage: $name <vol> <origin> <snapstore> [-i|--initialize] [-m|--metadev <device>] [-b|--blocksize <bytes>] [-c|--chunksize <bytes>] [-h|--help]"
+		declare mountpoint=$(mount_name $vol -1)
+		declare usage="Usage: $name <vol> <origin> <snapstore> [-i|--initialize] [-m|--metadev <device>] [-b|--blocksize <bytes>] [-c|--chunksize <bytes>] [-p|--mountpoint <dir>] [-h|--help]"
 
 		shift 2
-		args=`getopt -ob:c:m:hi -l blocksize:,chunksize:,help,metadev:,initialize -n"$name" -- "$@"` || { echo $usage; exit 2; }
+		args=`getopt -ob:c:m:hip: -l blocksize:,chunksize:,help,metadev:,initialize,mountpoint: -n"$name" -- "$@"` || { echo $usage; exit 2; }
 
 		eval set -- "$args" # remove getopt quotes and set new arguments
 
@@ -801,12 +805,15 @@ define)
 				echo "  -m, --metadev <device>  sets the metadata device (default is snapstore)"
 				echo "  -b, --blocksize <size>  user-specified block size (default is $blocksize)"
 				echo "  -c, --chunksize <size>  user-specified chunk size (default is $chunksize)"
+			#	echo "  -o, --mountopts <string> sets mount options for the volume"
+				echo "  -p, --mountpoint <dir>  sets the volume mountpoint (default is $MOUNTS)"
 				exit;;
 
 			-i|--initialize) init="yes";;
 			-m|--metadev) metadev=$2; shift 1;;
 			-b|--blocksize) blocksize=$2; shift 1;;
 			-c|--chunksize) chunksize=$2; shift 1;;
+			-p|--mountpoint) mountpoint=$2; shift 1;;
 			*) echo whoops; exit 9;;
 			esac
 			shift 1
@@ -821,10 +828,11 @@ define)
 		verify_managed_vol $vol && { echo "$0: volume '$vol' is already configured"; exit 1; }
 		verify_valid_device $origin || { echo "$0: invalid device '$origin'"; exit 1; }
 		verify_valid_device $snapstore || { echo "$0: invalid device '$snapstore'"; exit 1; }
+		verify_valid_mountpoint $mountpoint || { echo "$0: invalid mountpoint '$mountpoint'"; exit 1; }
 
 		[[ -z $metadev ]] || verify_valid_device $metadev || { echo "$0: invalid device '$metadev'"; exit 1; }
 		[[ -z $init ]] || ddsnap initialize --yes -c $chunksize $snapstore $origin $metadev || exit
-		define_volume $vol $origin $snapstore $metadev || { echo "$0: define volume '$vol' failed"; exit 1; }
+		define_volume $vol $origin $mountpoint $snapstore $metadev || { echo "$0: define volume '$vol' failed"; exit 1; }
 		exit ;;
 	target)
 		declare cmd="$0 $1 $2"
@@ -1351,6 +1359,22 @@ receive)
 		replication_cycle $vol $send_snap && rm $progressfile ;;
 	esac
 	exit
+	;;
+remount)
+	[[ $# -eq 3 ]] || { echo "usage: $0 remount <vol> <directory>"; exit 2; }
+	declare vol=$2
+	declare mountpoint=$3
+	declare mount=$(mount_name $vol -1)
+	declare -r mpath=$VOLUMES/$vol/filesystem
+
+	verify_managed_vol $vol || { echo "$0: volume '$vol' is not a managed volume"; exit 1; }
+	[[ $mountpoint = $mount ]] && { echo "$0: volume '$vol' is already mounted on $mount"; exit 1; }
+	mkdir -p $mpath
+	echo $mountpoint >$mpath/mountpoint
+
+	umount_device $vol -1 2>/dev/null
+	mount_device $vol -1 rw
+	exit $?
 	;;
 esac
 
