Handle snapshot mismatch downstream in the case of interrupted replication. Also read hold file in properly in the case the snapshot file is not renamed due to interruption.

diff --git a/trunk/zumastor/bin/zumastor b/trunk/zumastor/bin/zumastor
--- a/trunk/zumastor/bin/zumastor
+++ b/trunk/zumastor/bin/zumastor
@@ -38,7 +38,7 @@ function drop_snapshot {
 		usecount=$(ddsnap usecount $server $snap) || { log "couldn't get usecount for vol '$vol' snap '$snap'"; return 1; }
 		verify_valid_number $usecount || { log "usecount didn't return valid number '$usecount'"; return 1; }
 		[[ $usecount -eq 0 ]] && break
-		sleep 1
+		sleep 0.2
 	done
 		
 	ddsnap delete $server $snap || log "failed to delete snapshot '$vol($snap)'"
@@ -207,21 +207,36 @@ function replicate_snapshot {
 	local -r hold_file=$target_dir/hold
 	local -r server=$SERVERS/$vol
 	local -r port_file=$target_dir/port
-	local old_snap port status
+	local old_snap port status output
 
-	log "replication for snapshot '$snap' on volume '$vol' to '$host'"
+	read -d" " old_snap <$hold_file 2>/dev/null
 
-	read old_snap <$hold_file 2>/dev/null || log "error reading hold file, initial replication"
+	log "replication beginning from snapshot '$old_snap' to '$snap' on volume '$vol' for '$host'"
 
 	run_remote $host "cat $VOLUMES/$vol/source/hostname"
 	[[ $? -ne 0 ]] && { log "set '$MYHOSTNAME' as source for '$vol' on '$host' first!"; return 1; }
 
 	read port <$port_file || { log "error reading port from '$port_file'"; return 1; }
 
-	run_remote $host "zumastor receive start $vol $port $old_snap"
+	output=$(run_remote $host "zumastor receive start $vol $port $old_snap")
 	status=$?
-	[[ $status -eq 9 ]] && old_snap= && run_remote $host "zumastor receive start $vol $port" # fallback to initial volume
-	[[ $status -ne 0 ]] && { log "starting remote snapshot receive failed"; return 1; }
+	if [[ $status -eq 7 ]]; then # held snapshot mismatch
+		if verify_existing_snap $vol $output; then
+			log "downstream holding valid snapshot '$output', using it instead of '$old_snap'"
+			run_remote $host "zumastor receive start $vol $port $old_snap"
+			status=$?
+			[[ $status -eq 0 ]] && drop_snapshot $vol $old_snap
+			old_snap=$output
+		else
+			log "downstream holding invalid snapshot '$output', falling back to full volume"
+			run_remote $host "zumastor receive start $vol $port"
+			old_snap=
+		fi
+	fi
+	if [[ $status -ne 0 ]]; then
+		log "starting remote snapshot receive failed"
+		return 1
+	fi
 
 	echo $snap > $send_file
 
@@ -1146,8 +1161,8 @@ receive)
 		read hold <$holdfile 2>/dev/null
 		if [[ ! -z $snap ]] && [[ $snap != $hold ]]; then
 			log "mismatch incoming $snap, hold $hold" $log
-			echo "mismatch incoming $snap, hold $hold"
-			exit 2
+			echo $hold
+			exit 7
 		fi
 
 		# kill listen first in case it is already listening (previous replication interrupted)
