Fixed bug in replication delay cycle by using zumastor replicate.  Also fixed bug downstream to return success correctly.  Cleanups to make the code more readable.

diff --git a/trunk/zumastor/bin/zumastor b/trunk/zumastor/bin/zumastor
--- a/trunk/zumastor/bin/zumastor
+++ b/trunk/zumastor/bin/zumastor
@@ -29,20 +29,14 @@ function drop_snapshot {
 	local usecount
 
 	log "dropping snapshot for $vol($snap)"
-	usecount=$(ddsnap usecount $server $snap) || \
-		{ log "couldn't get usecount for vol '$vol' snap '$snap'"; return 1; }
-	[[ $usecount -eq 1 ]] || \
-		{ log "trying to remove snapshot with usecount '$usecount'"; return 1; }
-
-	remove_device $vol $snap || \
-		{ log "remove device failed for $vol($snap) "; return 1; }
+	usecount=$(ddsnap usecount $server $snap) || { log "couldn't get usecount for vol '$vol' snap '$snap'"; return 1; }
+	[[ $usecount -eq 1 ]] || { log "trying to remove snapshot with usecount '$usecount'"; return 1; }
+	remove_device $vol $snap || { log "remove device failed for $vol($snap) "; return 1; }
 
 	# FIXME we wait for the usecount to hit zero
 	while true; do
-		usecount=$(ddsnap usecount $server $snap) || \
-			{ log "couldn't get usecount for vol '$vol' snap '$snap'"; return 1; }
-		verify_valid_number $usecount || \
-			{ log "usecount didn't return valid number '$usecount'"; return 1; }
+		usecount=$(ddsnap usecount $server $snap) || { log "couldn't get usecount for vol '$vol' snap '$snap'"; return 1; }
+		verify_valid_number $usecount || { log "usecount didn't return valid number '$usecount'"; return 1; }
 		[[ $usecount -eq 0 ]] && break
 		sleep 1
 	done
@@ -56,8 +50,7 @@ function umount_drop_snapshot {
 	local -r snap=$2
 	local -r server=$SERVERS/$vol
 
-	umount_device $vol $snap || \
-		{ log "error umounting $vol($snap)"; return 1; }
+	umount_device $vol $snap || { log "error umounting $vol($snap)"; return 1; }
 
 	drop_snapshot $vol $snap || return 1
 }
@@ -214,38 +207,35 @@ function replicate_snapshot {
 	local -r hold_file=$target_dir/hold
 	local -r server=$SERVERS/$vol
 	local -r port_file=$target_dir/port
-	local old_snap rem_snap port
+	local old_snap port status
 
 	log "replication for snapshot '$snap' on volume '$vol' to '$host'"
 
-	read old_snap <$hold_file || { echo "initial replication"; }
+	read old_snap <$hold_file 2>/dev/null || log "error reading hold file, initial replication"
 
-	rem_snap=$(run_remote $host "cat $VOLUMES/$vol/source/hostname") && [[ $rem_snap == $MYHOSTNAME ]] || \
-		{ log "set '$MYHOSTNAME' as source for '$vol' on '$host' first!"; remove_device $vol $snap; return 1; }
+	run_remote $host "cat $VOLUMES/$vol/source/hostname"
+	[[ $? -ne 0 ]] && { log "set '$MYHOSTNAME' as source for '$vol' on '$host' first!"; return 1; }
 
 	read port <$port_file || { log "error reading port from '$port_file'"; return 1; }
 
-	rem_snap=$(run_remote $host "zumastor receive $vol $port start") || \
-		{ log "starting remote snapshot receive failed"; return 1; }
+	run_remote $host "zumastor receive start $vol $port $old_snap"
+	status=$?
+	[[ $status -eq 9 ]] && old_snap= && run_remote $host "zumastor receive start $vol $port" # fallback to initial volume
+	[[ $status -ne 0 ]] && { log "starting remote snapshot receive failed"; return 1; }
+
+	echo $snap > $send_file
 
 	log "remote listen for volume '$vol' on '$host:$port' started"
-
-	# in case of mismatch, do initial volume
-	[[ $old_snap -ne $rem_snap ]] && old_snap=""
-
 	# send the changes since the last snapshot via ddsnap transmit
-	# cleanup in case of failure so that we roll back to full volume replication next time
-	ddsnap transmit $server $host:$port -r -g 5 $old_snap $snap -p $send_file
+	ddsnap transmit $server $host:$port -r -g 1 $old_snap $snap -p $send_file
 	if [[ $? -ne 0 ]]; then
 		log "transmit $server $host:$port $old_snap $snap failed"
+		rm $hold_file # !!! FIXME we shouldn't always fall back to full volume
 		return 1
 	fi
 
-	run_remote $host "zumastor receive $vol $port done $snap"
-	if [[ $? -ne 0 ]]; then
-		log "zumastor receive $vol $port done $snap failed"
-		return 1
-	fi
+	run_remote $host "zumastor receive done $vol $port $snap"
+	[[ $? -ne 0 ]] && { log "zumastor receive done $vol $port $snap failed"; return 1; }
 
 	#[[ $snap -eq 5 ]] && restart_plug
 	# !!! FIXME TODO this is racy, we should save state by journaling
@@ -299,16 +289,19 @@ function run_master {
 	done &
 }
 
+function now {
+	date +%s
+}
+
 function run_target {
 	[ $# -eq 2 ] || { echo "$0: wrong argument count ($#: $@) in call: ${FUNCNAME[@]}"; exit 1; }
 	local -r vol=$1 host=$2
-
-	local -r fifo=$VOLUMES/$vol/targets/$host/trigger
-	local -r period_file=$VOLUMES/$vol/targets/$host/period
+	local -t target_dir=$VOLUMES/$vol/targets/$host
+	local -r fifo=$target_dir/trigger
+	local -r period_file=$target_dir/period
 	local -r log=${LOGS}/$vol/target-${host}.log
 	local -r master_fifo=$VOLUMES/$vol/master/trigger
-	local -r sleep_pid=$VOLUMES/$vol/targets/$host/.sleeppid
-	local snap state period spid
+	local snap period starttime newperiod delay
 
 	[ -r $fifo ] && [ -p $fifo ] || { log "target replication trigger '$fifo' is missing" $log; return 1; }
 
@@ -316,7 +309,7 @@ function run_target {
 
 	if [[ ! -z $period ]]; then
 		if verify_valid_number $period; then
-			trigger_replication $vol $host $snap
+			zumastor replicate $vol $host &
 		else
 			log "invalid period '$period' specified" $log
 			return 1
@@ -328,42 +321,50 @@ function run_target {
 
 	pid=""
 	while true; do
-		if [[ $pid == "" ]]; then
-			pid=$!
-			log "start daemon volume '$vol', target '$host', period '$period'" $log
-		fi
+		[[ $pid == "" ]] && pid=$! && log "start daemon volume '$vol', target '$host'" $log
 		# !!! FIXME TODO Implement skipping to most recent snapshot if there is a backlog
-
 		log "waiting for new snapshot..." $log
 
 		# wrap in a while loop because read will fail is ERESTARTSYS when the
 		# sleeping child exits
 		snap=""
 		while [[ $snap == "" ]]; do
-			[[ -r $fifo ]] || { log "$fifo not readable" $log; return 1; }
-			read snap <$fifo
-			sleep 1 # not necesary, just in case
+			read snap <$fifo && break || log "couldn't read from $fifo"
+			sleep 1
 		done
+		pkill -f "zumastor replicate $vol $host --delay"
+		starttime=$(now)
 
 		replicate_snapshot $vol $host $snap >> $log 2>&1
-		if [[ $? == 0 ]]; then #success 
+		if [[ $? -eq 0 ]]; then #success 
 			log "successfully replicated snapshot $snap" $log
-			[[ -z $period ]] || (
-				pid=$!
-				log "sleeper starting" $log
-				spid=""; read spid <$sleep_pid 2> /dev/null
-				[[ $spid != "" ]] && { log "killing sleeper $spid" $log; kill $spid; }
-				echo $pid > $sleep_pid
-				log "sleeping ${period}s for replication cycle" $log
-				sleep $period
-				log "sleep completed, triggering replication" $log
-				echo target $host > $VOLUMES/$vol/master/trigger
-				rm $sleep_pid
-				exit
-			) &
 		else
 			log "replicate error on snapshot $snap: $?" $log
 			drop_snapshot $vol $snap >> $log 2>&1
+		fi
+
+		read newperiod <$period_file 2>/dev/null || newperiod=
+		if [[ $newperiod != $period ]]; then
+			log "updated" $log
+			period=$newperiod
+			verify_valid_number $period || period=""
+			if [[ -z $period ]]; then
+				log "entering manual mode" $log
+			else
+				log "setting period to $period" $log
+			fi
+		fi
+
+		if [[ ! -z $period ]]; then
+			delay=$(( $(now) - $starttime ))
+			if [[ $delay -lt $period ]]; then
+				delay=$(( $period - $delay ))
+			else
+				delay=0
+			fi
+			# background this so the master and target daemons can't both block
+			log "scheduling replication cycle in ${delay}s" $log
+			zumastor replicate $vol $host --delay $delay &
 		fi
 	done &
 }
@@ -396,10 +397,12 @@ function stop_target {
 	[ $# -eq 2 ] || { echo "$0: wrong argument count ($#: $@) in call: ${FUNCNAME[@]}"; exit 1; }
 	local -r vol=$1
 	local -r host=$2
+	local -r log=${LOGS}/$vol/target-${host}.log
 
+	log "stopping target" $log
+	pkill -f "zumastor replicate $vol $host --delay"
 	pkill -f "zumastor start target $vol $host$" || return 1
 	pkill -f "ddsnap transmit $SERVERS/$vol $host:" || return 1
-	rm $VOLUMES/$vol/targets/$host/.sleeppid 2> /dev/null
 }
 
 function init_define_volume {
@@ -504,10 +507,12 @@ function define_target {
 	local -r port=$3
 	local -r period=$4
 	local -r path=$VOLUMES/$vol/targets/$host
+	local new=0
 
 	if [[ -e $path ]]; then
 		echo "$0: '$host' already set as target, updating configuration"
 	else
+		new=1
 		mkdir $path || return 1
 		mkfifo $path/trigger || return 1
 	fi
@@ -515,12 +520,17 @@ function define_target {
 	echo $port > $path/port || return 1
 	if [[ -z $period ]]; then
 		rm $path/period 2> /dev/null
+		[[ $new == 0 ]] && pkill -f "zumastor replicate $vol $host --delay"
 	else
 		echo $period > $path/period || return 1
+		if [[ $new == 0 ]]; then
+			pkill -f "zumastor replicate $vol $host --delay"
+			zumastor replicate $vol $host --delay $period & # FIXME calculate delay based on last replication time
+		fi
+			
 	fi
 
-	stop_target $vol $host 2>/dev/null
-	zumastor start target $vol $host || return 1
+	[[ $new == 1 ]] && zumastor start target $vol $host || return 1
 }
 
 function forget_target {
@@ -698,7 +708,7 @@ function replication_cycle {
 	log "replication cycle beginning - snapshot ($hold, $next)..." $log
 
 	log "creating snapshot..." $log
-	create_snapshot $vol $next >> $log 2>&1
+	create_snapshot $vol $next >> $log 2>&1 || { log "error creating new snapshot '$next'" $log; return 1; }
 
 	log "creating device..." $log
 	create_device $vol $next >> $log 2>&1
@@ -728,6 +738,7 @@ function replication_cycle {
 	fi
 
 	log "cycle complete" $log
+	return 0 # we only fail if create fails
 }
 
 # nag_daemon
@@ -771,26 +782,22 @@ case $1 in
 define)
 	case $2 in
 	volume)
-		declare args
-		declare metadev=""
-		declare noinit="noinit"
 		declare name="$0 $1 $2"
-
-		# these are the defaults
+		declare noinit="noinit"
+		declare args metadev
 		declare blocksize=4k
 		declare chunksize=16k
+		declare usage="Usage: $name <vol> <origin> <snapstore> [-i|--initialize] [-m|--metadev <device>] [-b|--blocksize <bytes>] [-c|--chunksize <bytes>] [-h|--help]"
 
 		shift 2
-		args=`getopt -ob:c:m:hi -l blocksize:,chunksize:,help,metadev:,initialize -n"$name" -- "$@"` || \
-			{ echo "usage: $name <vol> <origin> <snapstore> [Options]"; exit 2; }
+		args=`getopt -ob:c:m:hi -l blocksize:,chunksize:,help,metadev:,initialize -n"$name" -- "$@"` || { echo $usage; exit 2; }
 
 		eval set -- "$args" # remove getopt quotes and set new arguments
 
 		until [[ $1 = -- ]] ; do
 			case "$1" in
 			-h|--help)
-				echo "usage: $name <vol> <origin> <snapstore> [Options]"
-				echo "Options"
+				echo "$usage"
 				echo "  -h, --help              show this help"
 				echo "  -i, --initialize        initialize the volume with zeros (will destroy data)"
 				echo "  -m, --metadev <device>  sets the metadata device (default is snapstore)"
@@ -805,10 +812,8 @@ define)
 			esac
 			shift 1
 		done
-
 		shift # remove --
-		[[ $# = 3 ]] || { echo "usage: $name <vol> <origin> <snapstore> [Options]"; exit 2; }
-
+		[[ $# = 3 ]] || { echo $usage; exit 2; }
 		declare vol=$1
 		declare origin=$2
 		declare snapstore=$3
@@ -1046,14 +1051,41 @@ snapshot)
 	exit $?
 	;;
 replicate)
-	[[ $# -eq 3 ]] || [[ $# -eq 4 ]] || { echo "usage: $0 replicate <vol> <host> [snap]"; exit 2; }
-	declare vol=$2
-	declare host=$3
-	declare snap=$4
+	declare name="$0 $1"
+	declare usage="Usage: $name <vol> <host> [-s|--snapnum <snapnum>] [-d|--delay <seconds>] [-h|--help]"
+	declare snap delay
+
+	shift 1
+	args=`getopt -os:d:hi -l size:,delay:,help, -n"$name" -- "$@"` || { echo $usage; exit 2; }
+
+	eval set -- "$args" # remove getopt quotes and set new arguments
+
+	until [[ $1 = -- ]] ; do
+		case "$1" in
+		-h|--help)
+			echo $usage
+			echo "  -h, --help            show this help"
+			echo "  -s, --snapnum <snap>  send specified snapshot (otherwise take a new snapshot)"
+			echo "  -d, --delay <seconds> wait specified number of seconds before replicating (default is 0)"
+			exit;;
+		-s|--snapnum) snap=$2; shift 1;;
+		-d|--delay) delay=$2; shift 1;;
+		*) echo whoops; exit 9;;
+		esac
+		shift 1
+	done
+	shift # remove --
+	[[ $# -eq 2 ]] || { echo $usage; exit 2; }
+	declare vol=$1
+	declare host=$2
 
 	verify_managed_vol $vol || { echo "$0: volume '$vol' is not a managed volume"; exit 1; }
 	verify_existing_target $vol $host || { echo "$0: host '$host' is not a target for volume '$vol'"; exit 1; }
-	[ -z $snap ] || verify_existing_snap $vol $snap || { echo "$0: invalid snapshot '$snap' for volume '$vol'"; exit 1; }
+	[[ -z $snap ]] || verify_existing_snap $vol $snap || { echo "$0: invalid snapshot '$snap' for volume '$vol'"; exit 1; }
+	if [[ ! -z $delay ]]; then
+		verify_valid_number $delay || { echo "$0: invalid delay '$delay' specified"; exit 1; }
+		sleep $delay
+	fi
 
 	# <snap> is optional and a new snapshot is taken if omitted
 	trigger_replication $vol $host $snap
@@ -1099,49 +1131,44 @@ status)
 	;;
 receive)
 	# called via upstream host's ssh command to start/stop listen
-	[ $# -ge 4 ] || { echo "usage: $0 receive <vol> <port> {start|done <snap>}"; exit 2; }
-	declare vol=$2
-	declare port=$3
-	declare startstop=$4
+	[[ $# -eq 4 ]] || [[ $# -eq 5 ]] || { echo "usage: $0 receive {start|done} <vol> <port> [snap]}"; exit 2; }
+	declare startstop=$2
+	declare vol=$3
+	declare port=$4
+	declare snap=$5
 	declare holdfile=$VOLUMES/$vol/source/hold
 	declare log=${LOGS}/$vol/delta.log
-	declare rpid
-	declare snap
+	declare hold
 
 	verify_managed_vol $vol || { echo "$0: volume '$vol' is not a managed volume"; exit 1; }
 
 	case $startstop in
 	start)
-		[ $# -eq 4 ] || { echo "usage: $0 receive <vol> <port> start"; exit 2; }
-		# !!! FIXME TODO if the hold file doesn't exist
-		# assume we are initializing replication at snapshot 0
-		read snap <$holdfile 2>/dev/null
+		read hold <$holdfile 2>/dev/null
+		if [[ ! -z $snap ]] && [[ $snap != $hold ]]; then
+			log "mismatch incoming $snap, hold $hold" $log
+			echo "mismatch incoming $snap, hold $hold"
+			exit 2
+		fi
 
-		# start the listen daemon
+		# kill listen first in case it is already listening (previous replication interrupted)
+		pkill -f "ddsnap delta listen /dev/mapper/$vol 0.0.0.0"
 		# FIXME TODO - for now we listen on 0.0.0.0 and we don't check where
 		# the request came from, in the future, to avoid doing something
 		# wrong, such as replicatin from 2 hosts, check the $SSH_CLIENT
 		# environment variable
-
-		# kill listen first in case it is already listening (previous replication interrupted)
-		pkill -f "ddsnap delta listen /dev/mapper/$vol 0.0.0.0"
-
-		rpid=$(ddsnap delta listen /dev/mapper/$vol 0.0.0.0:$port -l $log)
-
-		# if successful, ouput should be "pid = <pid>"
-		rpid=${rpid/pid = /}
-
-		# if successful, send the hold snapid back to the caller
-		[[ $rpid -gt 1 ]] && echo $snap
-		exit $? ;;
+		ddsnap delta listen /dev/mapper/$vol 0.0.0.0:$port -l $log
+		if [[ $? -ne 0 ]]; then
+			log "failed to start listen" $log
+			echo "failed to start listen"
+			exit 2
+		fi ;;
 	done)
-		[ $# -eq 5 ] || { echo "usage: $0 receive <vol> <port> done <snap>"; exit 2; }
 		pkill -f "ddsnap delta listen /dev/mapper/$vol 0.0.0.0"
-		snap=$5
-		replication_cycle $vol $snap
-
-		exit $? ;;
+		verify_valid_number $snap || { echo "snapnum '$snap' is not valid"; exit 1; }
+		replication_cycle $vol $snap ;;
 	esac
+	exit
 	;;
 esac
 
